services:
  - type: web
    name: livekit-voice-agent
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python agent.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_SECRET
        sync: false
